--------------------------------------------------------
--  DDL for Table ALERT
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."ALERT" 
   (	"NUM" NUMBER, 
	"ALERT_CONTENT" VARCHAR2(200 BYTE) DEFAULT '알림이 존재하지 않습니다.', 
	"USER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."ALERT"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."ALERT"."ALERT_CONTENT" IS '알림내용';
   COMMENT ON COLUMN "SOMOIM"."ALERT"."USER_ID" IS '받는사람';
--------------------------------------------------------
--  DDL for Table COMMUNITY_BOARD
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."COMMUNITY_BOARD" 
   (	"NUM" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"SAVE_IMG" VARCHAR2(200 BYTE), 
	"WRITE_DATE" DATE DEFAULT sysdate, 
	"VIEW_COUNT" NUMBER DEFAULT 0, 
	"GOOD_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_BOARD"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_BOARD"."TITLE" IS '글제목';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_BOARD"."USER_ID" IS '작성자 아이디';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_BOARD"."CONTENT" IS '글내용';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_BOARD"."SAVE_IMG" IS '사진이름';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_BOARD"."WRITE_DATE" IS '작성시간';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_BOARD"."VIEW_COUNT" IS '조회수';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_BOARD"."GOOD_COUNT" IS '좋아요';
--------------------------------------------------------
--  DDL for Table COMMUNITY_COMMENTS
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."COMMUNITY_COMMENTS" 
   (	"NUM" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"WRITE_DATE" DATE DEFAULT sysdate, 
	"GOOD_COUNT" NUMBER DEFAULT 0, 
	"BOARD_NUM" NUMBER, 
	"PARENT_COM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_COMMENTS"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_COMMENTS"."USER_ID" IS '작성자 아이디';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_COMMENTS"."CONTENT" IS '댓글내용';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_COMMENTS"."WRITE_DATE" IS '작성시간';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_COMMENTS"."GOOD_COUNT" IS '좋아요';
   COMMENT ON COLUMN "SOMOIM"."COMMUNITY_COMMENTS"."BOARD_NUM" IS '게시글넘버';
--------------------------------------------------------
--  DDL for Table COMMUNITY_GOOD_COUNT_LIST
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."COMMUNITY_GOOD_COUNT_LIST" 
   (	"USER_ID" VARCHAR2(200 BYTE), 
	"LIST_NUM" NUMBER, 
	"NUM" NUMBER, 
	"GOOD_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CS_BUG
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."CS_BUG" 
   (	"NUM" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."CS_BUG"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."CS_BUG"."USER_ID" IS '신고자 아이디';
   COMMENT ON COLUMN "SOMOIM"."CS_BUG"."TITLE" IS '제목';
   COMMENT ON COLUMN "SOMOIM"."CS_BUG"."CONTENT" IS '내용';
--------------------------------------------------------
--  DDL for Table FOLLOWER
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."FOLLOWER" 
   (	"NUM" NUMBER, 
	"FOLLOWER_ID" VARCHAR2(200 BYTE), 
	"USER_ID" VARCHAR2(100 BYTE), 
	"FOLLOWER_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."FOLLOWER"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."FOLLOWER"."FOLLOWER_ID" IS '팔로워 아이디';
   COMMENT ON COLUMN "SOMOIM"."FOLLOWER"."USER_ID" IS '내 아이디';
   COMMENT ON COLUMN "SOMOIM"."FOLLOWER"."FOLLOWER_COUNT" IS '팔로워 수';
--------------------------------------------------------
--  DDL for Table FOLLOWING
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."FOLLOWING" 
   (	"NUM" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"FOLLOWING_ID" VARCHAR2(500 BYTE), 
	"FOLLOWING_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."FOLLOWING"."USER_ID" IS '내 아이디';
   COMMENT ON COLUMN "SOMOIM"."FOLLOWING"."FOLLOWING_ID" IS '팔로잉 아이디';
   COMMENT ON COLUMN "SOMOIM"."FOLLOWING"."FOLLOWING_COUNT" IS '팔로잉 수';
--------------------------------------------------------
--  DDL for Table GOOD_COUNT_LIST
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."GOOD_COUNT_LIST" 
   (	"USER_ID" VARCHAR2(200 BYTE), 
	"LIST_NUM" NUMBER, 
	"NUM" NUMBER, 
	"GOOD_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MESSAGE
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."MESSAGE" 
   (	"NUM" NUMBER, 
	"MSG_TITLE" VARCHAR2(50 BYTE), 
	"RECEIVER_ID" VARCHAR2(50 BYTE), 
	"GUBUN" NUMBER DEFAULT 0, 
	"CREATE_DATE" VARCHAR2(50 BYTE), 
	"MSG_CONTENT" VARCHAR2(500 BYTE), 
	"SENDER_ID" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"READ_YN" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."MESSAGE"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."MESSAGE"."MSG_TITLE" IS '쪽지 제목';
   COMMENT ON COLUMN "SOMOIM"."MESSAGE"."RECEIVER_ID" IS '수신자 아이디';
   COMMENT ON COLUMN "SOMOIM"."MESSAGE"."GUBUN" IS '수신/발신 구분';
   COMMENT ON COLUMN "SOMOIM"."MESSAGE"."CREATE_DATE" IS '수신/발신 날짜';
   COMMENT ON COLUMN "SOMOIM"."MESSAGE"."MSG_CONTENT" IS '쪽지 내용';
   COMMENT ON COLUMN "SOMOIM"."MESSAGE"."SENDER_ID" IS '발신자 아이디';
   COMMENT ON COLUMN "SOMOIM"."MESSAGE"."USER_ID" IS '유저 아이디';
   COMMENT ON COLUMN "SOMOIM"."MESSAGE"."READ_YN" IS '읽음표시';
--------------------------------------------------------
--  DDL for Table MYFEED
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."MYFEED" 
   (	"NUM" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"SAVE_NAME" VARCHAR2(100 BYTE) DEFAULT 'default_profile.png', 
	"GOOD_COUNT" NUMBER DEFAULT 0, 
	"HATE_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."MYFEED"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."MYFEED"."USER_ID" IS '아이디';
   COMMENT ON COLUMN "SOMOIM"."MYFEED"."SAVE_NAME" IS '프로필사진';
   COMMENT ON COLUMN "SOMOIM"."MYFEED"."GOOD_COUNT" IS '좋아요';
   COMMENT ON COLUMN "SOMOIM"."MYFEED"."HATE_COUNT" IS '신고';
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."NOTICE" 
   (	"NUM" NUMBER, 
	"USER_ID" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"WRITE_DATE" DATE DEFAULT SYSDATE, 
	"SAVE_NAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."NOTICE"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."NOTICE"."USER_ID" IS '아이디';
   COMMENT ON COLUMN "SOMOIM"."NOTICE"."TITLE" IS '글제목';
   COMMENT ON COLUMN "SOMOIM"."NOTICE"."CONTENT" IS '글내용';
   COMMENT ON COLUMN "SOMOIM"."NOTICE"."WRITE_DATE" IS '글작성시간';
   COMMENT ON COLUMN "SOMOIM"."NOTICE"."SAVE_NAME" IS '이지미파일명';
--------------------------------------------------------
--  DDL for Table SOMOIM
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."SOMOIM" 
   (	"NUM" NUMBER, 
	"SOM_TITLE" VARCHAR2(100 BYTE), 
	"CATEGORY" VARCHAR2(100 BYTE), 
	"MAX_MEMBER" NUMBER DEFAULT 50, 
	"CREATE_DATE" DATE DEFAULT sysdate, 
	"AREA" VARCHAR2(200 BYTE), 
	"SOM_CONTENT" VARCHAR2(2000 BYTE), 
	"SOMOIM_IMG" VARCHAR2(200 BYTE) DEFAULT '0112.png', 
	"SOMOIM_MASTER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."SOMOIM"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM"."SOM_TITLE" IS '소모임이름';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM"."CATEGORY" IS '소모임 카테고리';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM"."MAX_MEMBER" IS '멤버정원';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM"."CREATE_DATE" IS '개설날짜';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM"."AREA" IS '지역';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM"."SOM_CONTENT" IS '소모임 소개';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM"."SOMOIM_IMG" IS '소모임 대표사진';
--------------------------------------------------------
--  DDL for Table SOMOIM_BOARD
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."SOMOIM_BOARD" 
   (	"NUM" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"SAVE_NAME" VARCHAR2(200 BYTE), 
	"WRITE_DATE" DATE DEFAULT SYSDATE, 
	"VIEW_COUNT" NUMBER DEFAULT 0, 
	"GOOD_COUNT" NUMBER DEFAULT 0, 
	"VOTE_NUM" NUMBER, 
	"SOM_MEMBER_NUM" NUMBER, 
	"SOMOIM_NUM" NUMBER, 
	"SAVE_IMAGE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD"."TITLE" IS '글제목';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD"."CONTENT" IS '글내용';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD"."SAVE_NAME" IS '사진이름';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD"."WRITE_DATE" IS '작성시간';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD"."VIEW_COUNT" IS '조회수';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD"."GOOD_COUNT" IS '좋아요';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD"."VOTE_NUM" IS '투표테이블번호';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD"."SOM_MEMBER_NUM" IS '게시글 작성자 고유번호';
--------------------------------------------------------
--  DDL for Table SOMOIM_BOARD_COMMENTS
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."SOMOIM_BOARD_COMMENTS" 
   (	"NUM" NUMBER, 
	"SOM_MEMBER_NUM" NUMBER, 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"WRITE_DATE" DATE DEFAULT sysdate, 
	"GOOD_COUNT" NUMBER DEFAULT 0, 
	"SOM_BOARD_NUM" NUMBER, 
	"SOMOIM_NUM" NUMBER, 
	"SOM_COMMENT_DEPTH" NUMBER, 
	"PARENT_COM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD_COMMENTS"."NUM" IS 'PK';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD_COMMENTS"."SOM_MEMBER_NUM" IS '댓글 작성자 고유번호';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD_COMMENTS"."CONTENT" IS '댓글 내용';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD_COMMENTS"."WRITE_DATE" IS '댓글 작성 날짜';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD_COMMENTS"."GOOD_COUNT" IS '좋아요';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_BOARD_COMMENTS"."SOM_BOARD_NUM" IS '게시글 번호';
--------------------------------------------------------
--  DDL for Table SOMOIM_CHOICE_VOTE
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."SOMOIM_CHOICE_VOTE" 
   (	"NUM" NUMBER, 
	"SOM_QVOTE_NUM" NUMBER, 
	"CHOICE" VARCHAR2(50 BYTE), 
	"COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."SOMOIM_CHOICE_VOTE"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_CHOICE_VOTE"."SOM_QVOTE_NUM" IS '투표 제목';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_CHOICE_VOTE"."CHOICE" IS '투표 항목';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_CHOICE_VOTE"."COUNT" IS '투표수';
--------------------------------------------------------
--  DDL for Table SOMOIM_MEMBER
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."SOMOIM_MEMBER" 
   (	"NUM" NUMBER, 
	"USER_ID" VARCHAR2(100 BYTE), 
	"JOIN_DATE" DATE DEFAULT SYSDATE, 
	"POSITION" VARCHAR2(100 BYTE) DEFAULT '모임원', 
	"SOM_TITLE" VARCHAR2(200 BYTE), 
	"SAVE_NAME" VARCHAR2(200 BYTE) DEFAULT 'default.png', 
	"SOMOIM_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."SOMOIM_MEMBER"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_MEMBER"."USER_ID" IS '아이디';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_MEMBER"."JOIN_DATE" IS '가입날짜';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_MEMBER"."POSITION" IS '직급';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_MEMBER"."SOM_TITLE" IS '소모임이름';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_MEMBER"."SAVE_NAME" IS '이미파일명';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_MEMBER"."SOMOIM_NUM" IS '소모임 고유번호';
--------------------------------------------------------
--  DDL for Table SOMOIM_PAY
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."SOMOIM_PAY" 
   (	"NUM" NUMBER, 
	"MONEY" NUMBER, 
	"SOM_SCHEDULE_NUM" NUMBER, 
	"BANK_ACCOUNT" VARCHAR2(50 BYTE), 
	"PAY_COMPLETE_PARTICIPANT" VARCHAR2(200 BYTE), 
	"PARTICIPANT" VARCHAR2(200 BYTE), 
	"SADARI" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."SOMOIM_PAY"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_PAY"."MONEY" IS '정산 금액';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_PAY"."SOM_SCHEDULE_NUM" IS '일정 고유번호';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_PAY"."BANK_ACCOUNT" IS '일정 생성자 계좌번호';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_PAY"."PAY_COMPLETE_PARTICIPANT" IS '정산 완료자 목록';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_PAY"."PARTICIPANT" IS '참여자 목록';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_PAY"."SADARI" IS '사다리타기';
--------------------------------------------------------
--  DDL for Table SOMOIM_QUESTION_VOTE
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."SOMOIM_QUESTION_VOTE" 
   (	"NUM" NUMBER, 
	"SOM_MEMBER_NUM" NUMBER, 
	"QUESTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."SOMOIM_QUESTION_VOTE"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_QUESTION_VOTE"."SOM_MEMBER_NUM" IS '투표 생성자 고유번호';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_QUESTION_VOTE"."QUESTION" IS '투표 제목';
--------------------------------------------------------
--  DDL for Table SOMOIM_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."SOMOIM_SCHEDULE" 
   (	"NUM" NUMBER, 
	"SCHEDULE_DATE" VARCHAR2(100 BYTE), 
	"SCHEDULE_TIME" VARCHAR2(100 BYTE), 
	"SCHEDULE_TITLE" VARCHAR2(100 BYTE), 
	"PLACE" VARCHAR2(100 BYTE), 
	"MONEY" NUMBER, 
	"SOM_MEMBER_NUM" NUMBER, 
	"PARTICIPANT" VARCHAR2(2000 BYTE), 
	"PARTICIPANT_COUNT" NUMBER, 
	"SOMOIM_NUM" NUMBER, 
	"USER_ID" VARCHAR2(200 BYTE), 
	"MAX_PARTICIPANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."SOMOIM_SCHEDULE"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_SCHEDULE"."SCHEDULE_DATE" IS '일정 날짜';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_SCHEDULE"."SCHEDULE_TIME" IS '일정 시간';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_SCHEDULE"."SCHEDULE_TITLE" IS '일정 이름';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_SCHEDULE"."PLACE" IS '일정 장소';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_SCHEDULE"."MONEY" IS '참가비';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_SCHEDULE"."SOM_MEMBER_NUM" IS '일정 작성자 고유번호';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_SCHEDULE"."PARTICIPANT" IS '참가자 목록';
   COMMENT ON COLUMN "SOMOIM"."SOMOIM_SCHEDULE"."PARTICIPANT_COUNT" IS '참가자 수';
--------------------------------------------------------
--  DDL for Table USERINFO
--------------------------------------------------------

  CREATE TABLE "SOMOIM"."USERINFO" 
   (	"NUM" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"PW" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"SAVE_NAME" VARCHAR2(200 BYTE) DEFAULT 'default.png', 
	"MSG" VARCHAR2(2000 BYTE), 
	"ALERT" VARCHAR2(2000 BYTE), 
	"POINT" NUMBER DEFAULT 0, 
	"BIRTHDAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SOMOIM"."USERINFO"."NUM" IS 'pk';
   COMMENT ON COLUMN "SOMOIM"."USERINFO"."USER_ID" IS '아이디';
   COMMENT ON COLUMN "SOMOIM"."USERINFO"."PW" IS '비밀번호';
   COMMENT ON COLUMN "SOMOIM"."USERINFO"."NAME" IS '이름';
   COMMENT ON COLUMN "SOMOIM"."USERINFO"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "SOMOIM"."USERINFO"."SAVE_NAME" IS '프로필사진명';
   COMMENT ON COLUMN "SOMOIM"."USERINFO"."MSG" IS '쪽지';
   COMMENT ON COLUMN "SOMOIM"."USERINFO"."ALERT" IS '알림';
   COMMENT ON COLUMN "SOMOIM"."USERINFO"."POINT" IS '포인트';
   COMMENT ON COLUMN "SOMOIM"."USERINFO"."BIRTHDAY" IS '생년월일';
--------------------------------------------------------
--  DDL for Index ALERT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."ALERT_PK" ON "SOMOIM"."ALERT" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMUNITY_BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."COMMUNITY_BOARD_PK" ON "SOMOIM"."COMMUNITY_BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMUNITY_COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."COMMUNITY_COMMENTS_PK" ON "SOMOIM"."COMMUNITY_COMMENTS" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CS_BUG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."CS_BUG_PK" ON "SOMOIM"."CS_BUG" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOLLOWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."FOLLOWER_PK" ON "SOMOIM"."FOLLOWER" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOLLOWING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."FOLLOWING_PK" ON "SOMOIM"."FOLLOWING" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MESSAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."MESSAGE_PK" ON "SOMOIM"."MESSAGE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MYFEED_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."MYFEED_PK" ON "SOMOIM"."MYFEED" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOTICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."NOTICE_PK" ON "SOMOIM"."NOTICE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SOMOIM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."SOMOIM_PK" ON "SOMOIM"."SOMOIM" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SOMOIM_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."SOMOIM_UK1" ON "SOMOIM"."SOMOIM" ("SOM_TITLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SOMOIM_BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."SOMOIM_BOARD_PK" ON "SOMOIM"."SOMOIM_BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SOMOIM_BOARD_COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."SOMOIM_BOARD_COMMENTS_PK" ON "SOMOIM"."SOMOIM_BOARD_COMMENTS" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SOMOIM_CHOICE_VOTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."SOMOIM_CHOICE_VOTE_PK" ON "SOMOIM"."SOMOIM_CHOICE_VOTE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SOMOIM_MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."SOMOIM_MEMBER_PK" ON "SOMOIM"."SOMOIM_MEMBER" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SOMOIM_PAY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."SOMOIM_PAY_PK" ON "SOMOIM"."SOMOIM_PAY" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SOMOIM_QUESTION_VOTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."SOMOIM_QUESTION_VOTE_PK" ON "SOMOIM"."SOMOIM_QUESTION_VOTE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SOMOIM_SCHEDULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."SOMOIM_SCHEDULE_PK" ON "SOMOIM"."SOMOIM_SCHEDULE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."USERINFO_PK" ON "SOMOIM"."USERINFO" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERINFO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOMOIM"."USERINFO_UK1" ON "SOMOIM"."USERINFO" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ALERT
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."ALERT" ADD CONSTRAINT "ALERT_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."ALERT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."ALERT" MODIFY ("ALERT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."ALERT" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMUNITY_BOARD
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."COMMUNITY_BOARD" ADD CONSTRAINT "COMMUNITY_BOARD_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."COMMUNITY_BOARD" MODIFY ("GOOD_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_BOARD" MODIFY ("VIEW_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_BOARD" MODIFY ("WRITE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_BOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_BOARD" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMUNITY_COMMENTS
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."COMMUNITY_COMMENTS" ADD CONSTRAINT "COMMUNITY_COMMENTS_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."COMMUNITY_COMMENTS" MODIFY ("GOOD_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_COMMENTS" MODIFY ("WRITE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_COMMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_COMMENTS" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMUNITY_GOOD_COUNT_LIST
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."COMMUNITY_GOOD_COUNT_LIST" MODIFY ("GOOD_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_GOOD_COUNT_LIST" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_GOOD_COUNT_LIST" MODIFY ("LIST_NUM" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."COMMUNITY_GOOD_COUNT_LIST" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CS_BUG
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."CS_BUG" ADD CONSTRAINT "CS_BUG_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."CS_BUG" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."CS_BUG" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."CS_BUG" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."CS_BUG" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOLLOWER
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."FOLLOWER" ADD CONSTRAINT "FOLLOWER_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."FOLLOWER" MODIFY ("FOLLOWER_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."FOLLOWER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."FOLLOWER" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOLLOWING
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."FOLLOWING" ADD CONSTRAINT "FOLLOWING_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."FOLLOWING" MODIFY ("FOLLOWING_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."FOLLOWING" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."FOLLOWING" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GOOD_COUNT_LIST
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."GOOD_COUNT_LIST" MODIFY ("GOOD_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."GOOD_COUNT_LIST" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."GOOD_COUNT_LIST" MODIFY ("LIST_NUM" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."GOOD_COUNT_LIST" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MESSAGE
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."MESSAGE" ADD CONSTRAINT "MESSAGE_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."MESSAGE" MODIFY ("READ_YN" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MESSAGE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MESSAGE" MODIFY ("SENDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MESSAGE" MODIFY ("MSG_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MESSAGE" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MESSAGE" MODIFY ("GUBUN" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MESSAGE" MODIFY ("RECEIVER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MESSAGE" MODIFY ("MSG_TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MESSAGE" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MYFEED
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."MYFEED" ADD CONSTRAINT "MYFEED_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."MYFEED" MODIFY ("HATE_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MYFEED" MODIFY ("GOOD_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MYFEED" MODIFY ("SAVE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MYFEED" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."MYFEED" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."NOTICE" ADD CONSTRAINT "NOTICE_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."NOTICE" MODIFY ("WRITE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."NOTICE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."NOTICE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."NOTICE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."NOTICE" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOMOIM
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM" MODIFY ("SOMOIM_MASTER" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM" MODIFY ("SOMOIM_IMG" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM" MODIFY ("AREA" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM" MODIFY ("SOM_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM" MODIFY ("MAX_MEMBER" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM" ADD CONSTRAINT "SOMOIM_UK1" UNIQUE ("SOM_TITLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM" ADD CONSTRAINT "SOMOIM_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM" MODIFY ("SOM_TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOMOIM_BOARD
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_BOARD" ADD CONSTRAINT "SOMOIM_BOARD_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD" MODIFY ("SOM_MEMBER_NUM" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD" MODIFY ("GOOD_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD" MODIFY ("VIEW_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD" MODIFY ("WRITE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOMOIM_BOARD_COMMENTS
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_BOARD_COMMENTS" ADD CONSTRAINT "SOMOIM_BOARD_COMMENTS_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD_COMMENTS" MODIFY ("SOM_BOARD_NUM" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD_COMMENTS" MODIFY ("GOOD_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD_COMMENTS" MODIFY ("WRITE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD_COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD_COMMENTS" MODIFY ("SOM_MEMBER_NUM" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD_COMMENTS" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOMOIM_CHOICE_VOTE
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_CHOICE_VOTE" ADD CONSTRAINT "SOMOIM_CHOICE_VOTE_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM_CHOICE_VOTE" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_CHOICE_VOTE" MODIFY ("CHOICE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_CHOICE_VOTE" MODIFY ("SOM_QVOTE_NUM" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_CHOICE_VOTE" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOMOIM_MEMBER
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_MEMBER" ADD CONSTRAINT "SOMOIM_MEMBER_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM_MEMBER" MODIFY ("SAVE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_MEMBER" MODIFY ("SOM_TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_MEMBER" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_MEMBER" MODIFY ("JOIN_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_MEMBER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_MEMBER" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOMOIM_PAY
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_PAY" ADD CONSTRAINT "SOMOIM_PAY_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM_PAY" MODIFY ("PARTICIPANT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_PAY" MODIFY ("BANK_ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_PAY" MODIFY ("SOM_SCHEDULE_NUM" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_PAY" MODIFY ("MONEY" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_PAY" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOMOIM_QUESTION_VOTE
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_QUESTION_VOTE" ADD CONSTRAINT "SOMOIM_QUESTION_VOTE_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM_QUESTION_VOTE" MODIFY ("SOM_MEMBER_NUM" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_QUESTION_VOTE" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOMOIM_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_SCHEDULE" ADD CONSTRAINT "SOMOIM_SCHEDULE_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM_SCHEDULE" MODIFY ("SOM_MEMBER_NUM" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_SCHEDULE" MODIFY ("PLACE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_SCHEDULE" MODIFY ("SCHEDULE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_SCHEDULE" MODIFY ("SCHEDULE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_SCHEDULE" MODIFY ("SCHEDULE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."SOMOIM_SCHEDULE" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERINFO
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."USERINFO" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."USERINFO" ADD CONSTRAINT "USERINFO_UK1" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."USERINFO" ADD CONSTRAINT "USERINFO_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOMOIM"."USERINFO" MODIFY ("POINT" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."USERINFO" MODIFY ("SAVE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."USERINFO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."USERINFO" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."USERINFO" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."USERINFO" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOMOIM"."USERINFO" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMUNITY_BOARD
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."COMMUNITY_BOARD" ADD CONSTRAINT "COMMUNITY_BOARD_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SOMOIM"."USERINFO" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMUNITY_COMMENTS
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."COMMUNITY_COMMENTS" ADD CONSTRAINT "COMMUNITY_COMMENTS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SOMOIM"."USERINFO" ("USER_ID") ENABLE;
  ALTER TABLE "SOMOIM"."COMMUNITY_COMMENTS" ADD CONSTRAINT "COMMUNITY_COMMENTS_FK2" FOREIGN KEY ("BOARD_NUM")
	  REFERENCES "SOMOIM"."COMMUNITY_BOARD" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CS_BUG
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."CS_BUG" ADD CONSTRAINT "CS_BUG_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SOMOIM"."USERINFO" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOLLOWER
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."FOLLOWER" ADD CONSTRAINT "FOLLOWER_FK1" FOREIGN KEY ("FOLLOWER_ID")
	  REFERENCES "SOMOIM"."USERINFO" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOLLOWING
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."FOLLOWING" ADD CONSTRAINT "FOLLOWING_FK1" FOREIGN KEY ("FOLLOWING_ID")
	  REFERENCES "SOMOIM"."USERINFO" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MESSAGE
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."MESSAGE" ADD CONSTRAINT "MESSAGE_FK1" FOREIGN KEY ("RECEIVER_ID")
	  REFERENCES "SOMOIM"."USERINFO" ("USER_ID") ENABLE;
  ALTER TABLE "SOMOIM"."MESSAGE" ADD CONSTRAINT "MESSAGE_FK2" FOREIGN KEY ("SENDER_ID")
	  REFERENCES "SOMOIM"."USERINFO" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MYFEED
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."MYFEED" ADD CONSTRAINT "MYFEED_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SOMOIM"."USERINFO" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."NOTICE" ADD CONSTRAINT "NOTICE_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SOMOIM"."USERINFO" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOMOIM_BOARD
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_BOARD" ADD CONSTRAINT "SOMOIM_BOARD_FK1" FOREIGN KEY ("SOM_MEMBER_NUM")
	  REFERENCES "SOMOIM"."SOMOIM_MEMBER" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOMOIM_BOARD_COMMENTS
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_BOARD_COMMENTS" ADD CONSTRAINT "SOMOIM_BOARD_COMMENTS_FK1" FOREIGN KEY ("SOM_BOARD_NUM")
	  REFERENCES "SOMOIM"."SOMOIM_BOARD" ("NUM") ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM_BOARD_COMMENTS" ADD CONSTRAINT "SOMOIM_BOARD_COMMENTS_FK2" FOREIGN KEY ("SOM_MEMBER_NUM")
	  REFERENCES "SOMOIM"."SOMOIM_MEMBER" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOMOIM_CHOICE_VOTE
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_CHOICE_VOTE" ADD CONSTRAINT "SOMOIM_CHOICE_VOTE_FK1" FOREIGN KEY ("SOM_QVOTE_NUM")
	  REFERENCES "SOMOIM"."SOMOIM_QUESTION_VOTE" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOMOIM_MEMBER
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_MEMBER" ADD CONSTRAINT "SOMOIM_MEMBER_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SOMOIM"."USERINFO" ("USER_ID") ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM_MEMBER" ADD CONSTRAINT "SOMOIM_MEMBER_FK2" FOREIGN KEY ("SOM_TITLE")
	  REFERENCES "SOMOIM"."SOMOIM" ("SOM_TITLE") ENABLE;
  ALTER TABLE "SOMOIM"."SOMOIM_MEMBER" ADD CONSTRAINT "SOMOIM_MEMBER_FK3" FOREIGN KEY ("SOMOIM_NUM")
	  REFERENCES "SOMOIM"."SOMOIM" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOMOIM_PAY
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_PAY" ADD CONSTRAINT "SOMOIM_PAY_FK1" FOREIGN KEY ("SOM_SCHEDULE_NUM")
	  REFERENCES "SOMOIM"."SOMOIM_SCHEDULE" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOMOIM_QUESTION_VOTE
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_QUESTION_VOTE" ADD CONSTRAINT "SOMOIM_QUESTION_VOTE_FK1" FOREIGN KEY ("SOM_MEMBER_NUM")
	  REFERENCES "SOMOIM"."SOMOIM_MEMBER" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOMOIM_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "SOMOIM"."SOMOIM_SCHEDULE" ADD CONSTRAINT "SOMOIM_SCHEDULE_FK1" FOREIGN KEY ("SOM_MEMBER_NUM")
	  REFERENCES "SOMOIM"."SOMOIM_MEMBER" ("NUM") ENABLE;
